name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # or your default branch, e.g., master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository
        uses: actions/checkout@v4
        with:
          path: 'my-repo-checkout'

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5

      - name: Build and Copy Files (including hidden ones)
        run: |
          mkdir _site_output
          cd my-repo-checkout
          shopt -s dotglob
          cp -r * ../_site_output/
          shopt -u dotglob
          cd ..
          ls -la _site_output/

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '_site_output'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    # --- ADD THESE PERMISSIONS ---
    permissions:
      pages: write       # Grants write permission to the GITHUB_TOKEN for GitHub Pages deployment
      id-token: write    # Grants write permission to the GITHUB_TOKEN for OIDC token issuance
    # -----------------------------
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
