name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # or your default branch, e.g., master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository
        uses: actions/checkout@v4
        with:
          path: 'my-repo-checkout' # Checkout to a specific directory

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5

      - name: Build and Copy Files (including hidden ones)
        run: |
          # Create the temporary output directory OUTSIDE the checked-out repo
          mkdir _site_output

          # Copy all files from the checked-out repository root to _site_output,
          # including dotfiles and directories.
          # Use `shopt -s dotglob` within the source directory before copying.

          cd my-repo-checkout # Change to the checked-out repo directory
          shopt -s dotglob    # Enable dotglob to include dotfiles
          cp -r * ../_site_output/ # Copy all contents to the parent _site_output
          shopt -u dotglob    # Turn off dotglob
          cd .. # Change back to the parent directory where _site_output is

          # Optional: Verify content of _site_output
          ls -la _site_output/

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '_site_output' # The directory that contains your site's static files

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
